/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-04T09:53:57.710151

import 'package:zorphy_annotation/zorphy_annotation.dart';

import 'address.dart';
part 'user.g.dart';
part 'user.zorphy.dart';

/// User entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $User {
  String get id;
  String get name;
  $Address get address;
}
