/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:16:36.732934

import 'package:zorphy_annotation/zorphy_annotation.dart';
part 'user.zorphy.dart';
part 'user.g.dart';

/// User entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $User {
  String get name;
  int get age;
  String? get email;
}
