/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-04T09:53:58.688387

import 'package:zorphy_annotation/zorphy_annotation.dart';
part 'address.g.dart';
part 'address.zorphy.dart';

/// Address entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Address {
  String get street;
  String get city;
}
