/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06 20:58:38.415932

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../shape/shape.dart';

part 'rectangle.zorphy.dart';
part 'rectangle.g.dart';

/// Rectangle entity (subtype of Shape)
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Rectangle implements $$Shape {}
