/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:16:41.113369

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../payment_method/payment_method.dart';

part 'credit_card.zorphy.dart';
part 'credit_card.g.dart';

/// CreditCard entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CreditCard implements $$PaymentMethod {
  String get cardNumber;
  String get expiryDate;
}
