// Regression test for issue #127:
// "autoId entities cannot be compared by value — generated uuid leaks
//  into ==, hashCode, toJson and toJsonLean (silently breaks dedup/
//  Set/Map-key logic)".
//
// The fixture lives at `example/lib/various/issue127_value_equality_example.dart`
// and is regenerated by CI (`dart run build_runner build` in
// `zorphy/example`) before this test runs. The fixture declares three
// entities exercising every code path the fix touches:
//
//   1. `$AutoIdDefault` — `autoId: true` with NO `equalityExcludes`.
//      Back-compat default: `==`/`hashCode`/`toJsonLean()`/`compareToX()`
//      include `id`; the new `valueEquals`/`toJsonValue` methods drop
//      `id`.
//
//   2. `$AutoIdExcludesId` — `autoId: true` with `equalityExcludes:
//      ['id']`. Opt-out: `==`/`hashCode`/`toJsonLean()`/`compareToX()`
//      drop `id`; `toJson()` keeps `id` (persistence round-trip);
//      `valueEquals`/`toJsonValue` also drop `id`.
//
//   3. `$NonAutoIdExcludesCreatedAt` — non-autoId entity with
//      `equalityExcludes: ['createdAt']`. The `createdAt` metadata
//      field is dropped from `==`/`hashCode`/`toJsonLean()`/
//      `compareToX()`. No `valueEquals`/`toJsonValue` (autoId-only
//      surface).
//
// This is a golden test — it inspects the generated `.zorphy.dart`
// part file as text and asserts the expected code patterns. It does
// NOT instantiate the entity (the test package can't import the
// example package's generated code directly without more plumbing);
// the generated-code assertions are sufficient to prove the fix is
// correct, and the `dart analyze` step in CI proves the generated
// code compiles.
library test.regression.issue_127_value_equality_test;

import 'dart:io';

import 'package:test/test.dart';

void main() {
  final fixture =
      File('example/lib/various/issue127_value_equality_example.zorphy.dart');
  late String output;

  setUpAll(() {
    if (!fixture.existsSync()) {
      fail(
        'Fixture not generated. Run: cd example && '
        'dart run build_runner build --delete-conflicting-outputs',
      );
    }
    output = fixture.readAsStringSync();
  });

  // ── $AutoIdDefault — back-compat default ──────────────────────────

  group('AutoIdDefault (autoId + no equalityExcludes) — back-compat', () {
    test('operator == still includes id (back-compat with v2.x)', () {
      // The default == must still compare id, so existing code that
      // relies on identity equality keeps working.
      expect(
        output,
        contains('id == other.id &&\n        toolName == other.toolName &&\n'
            '        normalizedArgs == other.normalizedArgs;'),
      );
    });

    test('hashCode still includes id (back-compat with v2.x)', () {
      expect(
        output,
        contains('Object.hash(this.id, this.toolName, this.normalizedArgs)'),
      );
    });

    test('toJsonLean() does NOT remove id (back-compat with v2.x)', () {
      // No `data.remove('id');` inside AutoIdDefault's toJsonLean body.
      // We assert by finding the AutoIdDefault toJsonLean block and
      // verifying it does NOT contain the remove call.
      final block = _extractClassBlock(output, 'AutoIdDefault');
      final toJsonLeanBlock = _extractMethodBlock(block, 'toJsonLean');
      expect(
        toJsonLeanBlock,
        isNot(contains("data.remove('id')")),
        reason: 'Back-compat: toJsonLean keeps id when equalityExcludes is '
            'not set, so existing lean-output round-trips continue to work.',
      );
    });

    test('compareToAutoIdDefault() still reports id diffs (back-compat)',
        () {
      final compareToBlock = _extractExtensionMethodBlock(
        output,
        'AutoIdDefaultCompareE',
        'compareToAutoIdDefault',
      );
      expect(compareToBlock, contains("diff['id'] = () => other.id;"));
      expect(compareToBlock, contains("diff['toolName']"));
      expect(compareToBlock, contains("diff['normalizedArgs']"));
    });

    test('NEW: valueEquals() exists and compares toolName/normalizedArgs '
        'ONLY (drops id)', () {
      final block = _extractClassBlock(output, 'AutoIdDefault');
      expect(block, contains('bool valueEquals(Object other)'));
      final valueEqualsBlock = _extractMethodBlock(block, 'valueEquals');
      // valueEquals compares every field EXCEPT the autoId field `id`.
      expect(valueEqualsBlock, isNot(contains('id == other.id')));
      expect(valueEqualsBlock, contains('toolName == other.toolName'));
      expect(valueEqualsBlock, contains('normalizedArgs == other.normalizedArgs'));
    });

    test('NEW: toJsonValue() exists and removes id from the data map', () {
      final block = _extractClassBlock(output, 'AutoIdDefault');
      expect(block, contains('Map<String, dynamic> toJsonValue()'));
      final toJsonValueBlock = _extractMethodBlock(block, 'toJsonValue');
      expect(toJsonValueBlock, contains("data.remove('id');"));
      // toJsonValue keeps the semantic fields:
      expect(toJsonValueBlock, contains('_\$AutoIdDefaultToJson(this)'));
    });

    test('toJson() still includes id (persistence round-trip)', () {
      // The AutoIdExampleSerialization extension's toJson() body calls
      // _$AutoIdDefaultToJson(this), which includes id. We assert the
      // toJson extension exists; the full json_serializable output is
      // generated separately and asserted by dart analyze.
      expect(output, contains('AutoIdDefaultSerialization on AutoIdDefault'));
    });
  });

  // ── $AutoIdExcludesId — field-level opt-out ────────────────────────

  group('AutoIdExcludesId (autoId + equalityExcludes: [id]) — opt-out', () {
    test('operator == drops id (compares toolName/normalizedArgs ONLY)', () {
      final block = _extractClassBlock(output, 'AutoIdExcludesId');
      final equalsBlock = _extractOperatorEqualsBlock(block);
      expect(equalsBlock, isNot(contains('id == other.id')));
      expect(equalsBlock, contains('toolName == other.toolName'));
      expect(equalsBlock, contains('normalizedArgs == other.normalizedArgs'));
    });

    test('hashCode drops id (Object.hash(this.toolName, this.normalizedArgs))',
        () {
      final block = _extractClassBlock(output, 'AutoIdExcludesId');
      final hashCodeBlock = _extractMethodBlock(block, 'hashCode');
      expect(hashCodeBlock,
          contains('Object.hash(this.toolName, this.normalizedArgs)'));
      expect(hashCodeBlock, isNot(contains('this.id')));
    });

    test('toJsonLean() removes id from the data map', () {
      final block = _extractClassBlock(output, 'AutoIdExcludesId');
      final toJsonLeanBlock = _extractMethodBlock(block, 'toJsonLean');
      expect(toJsonLeanBlock, contains("data.remove('id');"));
    });

    test('compareToAutoIdExcludesId() does NOT report id diffs', () {
      final compareToBlock = _extractExtensionMethodBlock(
        output,
        'AutoIdExcludesIdCompareE',
        'compareToAutoIdExcludesId',
      );
      expect(compareToBlock, isNot(contains("diff['id']")));
      expect(compareToBlock, contains("diff['toolName']"));
      expect(compareToBlock, contains("diff['normalizedArgs']"));
    });

    test('toString() still includes id (debug output is NOT filtered)', () {
      final block = _extractClassBlock(output, 'AutoIdExcludesId');
      final toStringBlock = _extractMethodBlock(block, 'toString');
      expect(toStringBlock, contains("'id: \${id}'"));
      expect(toStringBlock, contains("'toolName: \${toolName}'"));
    });

    test('valueEquals() exists and compares toolName/normalizedArgs ONLY', () {
      final block = _extractClassBlock(output, 'AutoIdExcludesId');
      expect(block, contains('bool valueEquals(Object other)'));
      final valueEqualsBlock = _extractMethodBlock(block, 'valueEquals');
      expect(valueEqualsBlock, isNot(contains('id == other.id')));
      expect(valueEqualsBlock, contains('toolName == other.toolName'));
      expect(valueEqualsBlock, contains('normalizedArgs == other.normalizedArgs'));
    });

    test('toJsonValue() exists and removes id from the data map', () {
      final block = _extractClassBlock(output, 'AutoIdExcludesId');
      final toJsonValueBlock = _extractMethodBlock(block, 'toJsonValue');
      expect(toJsonValueBlock, contains("data.remove('id');"));
    });

    test('toJson() still keeps id (persistence round-trip — NOT filtered)',
        () {
      expect(
        output,
        contains('AutoIdExcludesIdSerialization on AutoIdExcludesId'),
      );
      // The toJson extension delegates to _$AutoIdExcludesIdToJson(this)
      // which json_serializable generates with ALL fields (including id).
      // We assert the call site exists; the full json_serializable output
      // is asserted by `dart analyze` (which would fail if id were dropped
      // from the toJson signature).
      expect(
        output,
        contains('_\$AutoIdExcludesIdToJson(this)'),
      );
    });
  });

  // ── $NonAutoIdExcludesCreatedAt — non-autoId opt-out ───────────────

  group('NonAutoIdExcludesCreatedAt (non-autoId + equalityExcludes: '
      '[createdAt]) — non-autoId opt-out', () {
    test('operator == drops createdAt (compares name/score ONLY)', () {
      final block = _extractClassBlock(output, 'NonAutoIdExcludesCreatedAt');
      final equalsBlock = _extractOperatorEqualsBlock(block);
      expect(equalsBlock, isNot(contains('createdAt == other.createdAt')));
      expect(equalsBlock, contains('name == other.name'));
      expect(equalsBlock, contains('score == other.score'));
    });

    test('hashCode drops createdAt (Object.hash(this.name, this.score))',
        () {
      final block = _extractClassBlock(output, 'NonAutoIdExcludesCreatedAt');
      final hashCodeBlock = _extractMethodBlock(block, 'hashCode');
      expect(hashCodeBlock, contains('Object.hash(this.name, this.score)'));
      expect(hashCodeBlock, isNot(contains('this.createdAt')));
    });

    test('toJsonLean() removes createdAt from the data map', () {
      final block = _extractClassBlock(output, 'NonAutoIdExcludesCreatedAt');
      final toJsonLeanBlock = _extractMethodBlock(block, 'toJsonLean');
      expect(toJsonLeanBlock, contains("data.remove('createdAt');"));
    });

    test('compareToNonAutoIdExcludesCreatedAt() does NOT report createdAt '
        'diffs', () {
      final compareToBlock = _extractExtensionMethodBlock(
        output,
        'NonAutoIdExcludesCreatedAtCompareE',
        'compareToNonAutoIdExcludesCreatedAt',
      );
      expect(compareToBlock, isNot(contains("diff['createdAt']")));
      expect(compareToBlock, contains("diff['name']"));
      expect(compareToBlock, contains("diff['score']"));
    });

    test('NO valueEquals() method (autoId-only surface)', () {
      final block = _extractClassBlock(output, 'NonAutoIdExcludesCreatedAt');
      expect(block, isNot(contains('valueEquals')));
    });

    test('NO toJsonValue() method (autoId-only surface)', () {
      final block = _extractClassBlock(output, 'NonAutoIdExcludesCreatedAt');
      expect(block, isNot(contains('toJsonValue')));
    });
  });
}

// ── helpers ────────────────────────────────────────────────────────

/// Returns the source slice of the class declaration for [className]
/// from the generated [output]. The slice starts at the class header
/// and ends at the matching closing brace.
String _extractClassBlock(String output, String className) {
  final headerPattern = RegExp('class $className \\{');
  final headerMatch = headerPattern.firstMatch(output);
  if (headerMatch == null) {
    fail('class $className not found in fixture output');
  }
  final start = headerMatch.start;
  // Walk braces to find the matching close.
  var depth = 0;
  for (var i = start; i < output.length; i++) {
    final ch = output[i];
    if (ch == '{') {
      depth++;
    } else if (ch == '}') {
      depth--;
      if (depth == 0) {
        return output.substring(start, i + 1);
      }
    }
  }
  fail('unterminated class $className block');
}

/// Returns the source slice of the `operator ==` method body inside
/// [block]. Searches for `operator ==` literally (word boundaries do
/// not work with `==` since `=` is not a word character).
String _extractOperatorEqualsBlock(String block) {
  final needle = 'operator ==';
  final idx = block.indexOf(needle);
  if (idx == -1) {
    fail('operator == not found in block');
  }
  final openIdx = block.indexOf('{', idx);
  if (openIdx == -1) {
    fail('no body found for operator == in block');
  }
  var depth = 0;
  for (var i = openIdx; i < block.length; i++) {
    final ch = block[i];
    if (ch == '{') {
      depth++;
    } else if (ch == '}') {
      depth--;
      if (depth == 0) {
        return block.substring(idx, i + 1);
      }
    }
  }
  fail('unterminated operator == block');
}

/// Returns the source slice of the named method inside the named
/// extension. Zorphy emits `compareToX` and `changeToX` as extension
/// methods (in `${className}CompareE` / `${className}ChangeToE`
/// respectively) — they are NOT inside the class body, so they must be
/// extracted from the extension block, not the class block.
String _extractExtensionMethodBlock(
  String output,
  String extensionName,
  String methodName,
) {
  // Find `extension <extensionName> on <Type> { ... }` and extract the
  // method body inside it.
  final extHeader = RegExp('extension $extensionName on \\w+ \\{');
  final extMatch = extHeader.firstMatch(output);
  if (extMatch == null) {
    fail('extension $extensionName not found in fixture output');
  }
  final extStart = extMatch.start;
  var depth = 0;
  String? extBlock;
  for (var i = extStart; i < output.length; i++) {
    final ch = output[i];
    if (ch == '{') {
      depth++;
    } else if (ch == '}') {
      depth--;
      if (depth == 0) {
        extBlock = output.substring(extStart, i + 1);
        break;
      }
    }
  }
  if (extBlock == null) {
    fail('unterminated extension $extensionName block');
  }
  // Find the method inside the extension.
  final namePattern = RegExp(r'\b' + RegExp.escape(methodName) + r'\b');
  final nameMatch = namePattern.firstMatch(extBlock);
  if (nameMatch == null) {
    fail('method $methodName not found in extension $extensionName');
  }
  final openIdx = extBlock.indexOf('{', nameMatch.start);
  if (openIdx == -1) {
    fail('no body found for $methodName in extension $extensionName');
  }
  depth = 0;
  for (var i = openIdx; i < extBlock.length; i++) {
    final ch = extBlock[i];
    if (ch == '{') {
      depth++;
    } else if (ch == '}') {
      depth--;
      if (depth == 0) {
        return extBlock.substring(nameMatch.start, i + 1);
      }
    }
  }
  fail('unterminated method $methodName in extension $extensionName');
}

/// Returns the source slice of the method [methodName] inside [block].
/// The slice starts at the method signature and ends at the matching
/// closing brace of the method body. Handles getters (no body) by
/// returning the signature line.
String _extractMethodBlock(String block, String methodName) {
  // Method declarations appear as either:
  //   <type> methodName(<params>) {
  //   <type> get methodName {
  //   <type> get methodName => ...;
  // We search for the method name as a word and then walk braces.
  final namePattern = RegExp(r'\b' + RegExp.escape(methodName) + r'\b');
  final nameMatch = namePattern.firstMatch(block);
  if (nameMatch == null) {
    fail('method $methodName not found in block');
  }
  // Find the opening brace AFTER the method name.
  final openIdx = block.indexOf('{', nameMatch.start);
  if (openIdx == -1) {
    // Getter with arrow body — return up to the next semicolon.
    final semiIdx = block.indexOf(';', nameMatch.start);
    if (semiIdx == -1) {
      fail('no body found for $methodName in block');
    }
    return block.substring(nameMatch.start, semiIdx + 1);
  }
  // Walk braces from openIdx.
  var depth = 0;
  for (var i = openIdx; i < block.length; i++) {
    final ch = block[i];
    if (ch == '{') {
      depth++;
    } else if (ch == '}') {
      depth--;
      if (depth == 0) {
        return block.substring(nameMatch.start, i + 1);
      }
    }
  }
  fail('unterminated method $methodName block');
}
