import 'model.dart';

/// Renders the markdown migration report.
class MigrationReport {
  final List<ConvertedClass> converted;
  final List<ManualItem> manualItems;

  /// Whether any converted model came from the `@ExchangeableObject` /
  /// `@ExchangeableEnum` dialect (vs freezed) — adjusts the next-steps.
  final bool hasExchangeable;

  MigrationReport({
    required this.converted,
    required this.manualItems,
    this.hasExchangeable = false,
  });

  String toMarkdown() {
    final sb = StringBuffer()
      ..writeln('# Model → Zorphy Migration Report')
      ..writeln()
      ..writeln('## Converted classes (${converted.length})')
      ..writeln();

    if (converted.isEmpty) {
      sb.writeln('_None._');
    } else {
      for (final c in converted) {
        final notes = c.notes.isEmpty ? '' : ' — ${c.notes.join('; ')}';
        sb.writeln('- `${c.className}` (${c.filePath})$notes');
      }
    }

    sb
      ..writeln()
      ..writeln('## Needs manual attention (${manualItems.length})')
      ..writeln();

    if (manualItems.isEmpty) {
      sb.writeln('_None — clean migration._');
    } else {
      for (final m in manualItems) {
        sb.writeln(
          '- `${m.filePath}:${m.line}` — `${m.construct}`: ${m.reason}',
        );
      }
    }

    sb
      ..writeln()
      ..writeln('## Next steps')
      ..writeln()
      ..writeln('1. Remove `freezed` and `freezed_annotation` from pubspec.yaml '
          'and add `zorphy` (dev) + `zorphy_annotation`.')
      ..writeln('2. Delete all `*.freezed.dart` files '
          '(and stale `*.g.dart` for converted classes).')
      ..writeln('3. Update `part` directives: drop `.freezed.dart`, '
          'keep `.g.dart` only when `generateJson: true` was emitted.')
      ..writeln('4. Replace `when`/`map` calls with Dart 3 `switch` '
          'expressions on the sealed base.')
      ..writeln('5. Run `dart run build_runner build '
          '--delete-conflicting-outputs`, then `dart analyze`.');

    if (hasExchangeable) {
      sb
        ..writeln()
        ..writeln('For `@ExchangeableObject`/`@ExchangeableEnum` sources '
            '(fork codegen, not freezed):')
        ..writeln('6. Swap the internal-annotations import for '
            '`package:zorphy_annotation/zorphy_annotation.dart` and add '
            '`part \'<file>.zorphy.dart\';` next to the existing `.g.dart` '
            'part.')
        ..writeln('7. Delete the stale codegen `.g.dart` (regenerated by '
            'json_serializable) and move the file into the package\'s zorphy '
            'builder scope if the build.yaml scopes entity generation.')
        ..writeln('8. Update barrels to re-export the entity under the '
            '`_`-stripped public name, and glue platform controllers '
            '(`fromMap`→`fromJson`, `toMap`→`toJson`, enum wire '
            '`_value`→`.index`/name).');
    }

    return sb.toString();
  }
}

/// A class the migrator converted successfully.
class ConvertedClass {
  final String className;
  final String filePath;
  final List<String> notes;

  const ConvertedClass(this.className, this.filePath, [this.notes = const []]);
}
