/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:16:42.574833

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../user/user.dart';

part 'company.zorphy.dart';
part 'company.g.dart';

/// Company entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Company {
  String get name;
  List<$User> get employees;
  List<String> get locations;
}
