import 'dart:io';
import 'package:path/path.dart' as p;
import 'models/entity_config.dart';
import 'services/field_normalizer.dart';
import 'services/import_resolver.dart';
import 'generators/entity_template_generator.dart';

/// Result for subtype generation
class SubtypeResult {
  final String className;
  final String filePath;
  final String content;
  final List<FieldDefinition> fields;

  const SubtypeResult({
    required this.className,
    required this.filePath,
    required this.content,
    required this.fields,
  });
}

/// Main orchestrator for creating Zorphy entities
class EntityCreator {
  final String baseOutputDir;

  EntityCreator({String? baseOutputDir})
    : baseOutputDir = baseOutputDir ?? 'lib/src/domain/entities';

  /// Create an entity and return the result
  Future<EntityResult> create(EntityConfig config) async {
    try {
      final effectiveOutputDir = config.outputDir ?? baseOutputDir;
      final normalizer = FieldNormalizer(baseOutputDir: effectiveOutputDir);
      final resolver = ImportResolver(baseOutputDir: effectiveOutputDir);

      final normalizedFields = config.fields
          .map((f) => normalizer.normalizeField(f))
          .toList();

      final normalizedConfig = config.copyWith(fields: normalizedFields);

      final imports = resolver.resolveImports(
        normalizedConfig.className,
        normalizedFields,
        extendsInterface: normalizedConfig.extendsInterface,
        explicitSubtypes: normalizedConfig.explicitSubtypes,
        generateSubtypes: normalizedConfig.generateSubtypes,
        isSealed: normalizedConfig.isSealed,
      );

      final content = EntityTemplateGenerator.generate(
        normalizedConfig,
        imports.toList(),
      );

      final entityDir = p.join(effectiveOutputDir, normalizedConfig.snakeName);
      final filePath = p.join(entityDir, '${normalizedConfig.snakeName}.dart');

      if (!config.dryRun) {
        await Directory(entityDir).create(recursive: true);
        await File(filePath).writeAsString(content);

        if (normalizedConfig.generateSubtypes &&
            normalizedConfig.explicitSubtypes.isNotEmpty) {
          await generateSubtypeFiles(normalizedConfig, {});
        }
      }

      return EntityResult(
        className: normalizedConfig.className,
        filePath: filePath,
        content: content,
        imports: imports.toList(),
        fields: normalizedFields,
        created: true,
      );
    } catch (e) {
      return EntityResult.failure(e.toString());
    }
  }

  /// Create an enum and return the result
  Future<EnumResult> createEnum(EnumConfig config) async {
    try {
      final effectiveOutputDir = config.outputDir ?? baseOutputDir;
      final enumsDir = p.join(effectiveOutputDir, 'enums');

      final buffer = StringBuffer();
      buffer.writeln('// Auto-generated by Zorphy');
      buffer.writeln('// Generated at: ${DateTime.now().toIso8601String()}');
      buffer.writeln();

      // Normalize every value into a (member, wire) pair. Supports explicit
      // "member:wire" syntax; otherwise the value is both the Dart member name
      // and the JSON wire value. Dart-reserved words (e.g. `as`, `is`) are
      // auto-escaped with a trailing `_` (zuraffa#306).
      final pairs = <(String, String)>[];
      for (final raw in config.values) {
        final value = raw.trim();
        if (value.isEmpty) continue;
        var member = value;
        String? wire;
        final colonIdx = value.indexOf(':');
        if (colonIdx > 0) {
          member = value.substring(0, colonIdx).trim();
          wire = value.substring(colonIdx + 1).trim();
        }
        if (wire == null || wire.isEmpty) wire = member;
        if (!_isValidDartIdentifier(member)) {
          member = '${member}_';
        }
        pairs.add((member, wire));
      }

      final needsJsonValue = pairs.any((p) => p.$1 != p.$2) && pairs.isNotEmpty;
      if (needsJsonValue) {
        buffer.writeln(
          "import 'package:json_annotation/json_annotation.dart';",
        );
        buffer.writeln();
      }
      buffer.writeln('enum ${config.className} {');

      for (var i = 0; i < pairs.length; i++) {
        final (member, wire) = pairs[i];
        if (wire != member) {
          buffer.writeln("  @JsonValue('$wire')");
        }
        buffer.writeln('  $member,');
      }

      buffer.writeln('}');
      buffer.writeln();

      final filePath = p.join(enumsDir, '${config.snakeName}.dart');
      final content = buffer.toString();

      if (!config.dryRun) {
        await Directory(enumsDir).create(recursive: true);
        await File(filePath).writeAsString(content);
        await _updateEnumIndexFile(enumsDir);
      }

      return EnumResult(
        enumName: config.className,
        filePath: filePath,
        content: content,
        created: true,
      );
    } catch (e) {
      return EnumResult.failure(e.toString());
    }
  }

  /// Add fields to an existing entity
  Future<EntityResult> addFields(
    String entityName,
    List<FieldDefinition> newFields, {
    String? outputDir,
    bool dryRun = false,
  }) async {
    try {
      final effectiveOutputDir = outputDir ?? baseOutputDir;
      final normalizer = FieldNormalizer(baseOutputDir: effectiveOutputDir);

      final className = _formatClassName(entityName);
      final snakeName = _toSnakeCase(className);
      final entityDir = p.join(effectiveOutputDir, snakeName);
      final filePath = p.join(entityDir, '$snakeName.dart');
      final file = File(filePath);

      if (!file.existsSync()) {
        return EntityResult.failure('Entity not found at $filePath');
      }

      final content = await file.readAsString();
      final normalizedFields = newFields
          .map((f) => normalizer.normalizeField(f))
          .toList();

      final updatedContent = _insertFields(
        content,
        className,
        normalizedFields,
      );

      if (!dryRun) {
        await file.writeAsString(updatedContent);
      }

      return EntityResult(
        className: className,
        filePath: filePath,
        content: updatedContent,
        fields: normalizedFields,
        created: true,
      );
    } catch (e) {
      return EntityResult.failure(e.toString());
    }
  }

  /// Generate subtypes for a sealed class (inline in same file)
  Future<List<SubtypeResult>> generateInlineSubtypes(
    EntityConfig parentConfig,
    Map<String, List<FieldDefinition>> subtypeFields,
  ) async {
    final results = <SubtypeResult>[];

    for (final subtype in parentConfig.explicitSubtypes) {
      final subtypeName = subtype.replaceAll('\$', '');
      final className = _formatClassName(subtypeName);
      final fields = subtypeFields[subtype] ?? [];

      final content = EntityTemplateGenerator.generateInlineSubtype(
        className,
        parentConfig.className,
        parentConfig.isSealed,
        fields,
        parentConfig,
      );

      results.add(
        SubtypeResult(
          className: className,
          filePath: '',
          content: content,
          fields: fields,
        ),
      );
    }

    return results;
  }

  /// Generate subtypes as separate files
  Future<List<EntityResult>> generateSubtypeFiles(
    EntityConfig parentConfig,
    Map<String, List<FieldDefinition>> subtypeFields,
  ) async {
    final results = <EntityResult>[];
    final effectiveOutputDir = parentConfig.outputDir ?? baseOutputDir;
    final resolver = ImportResolver(baseOutputDir: effectiveOutputDir);

    for (final subtype in parentConfig.explicitSubtypes) {
      // Support name:wireValue format (e.g. "DefaultDisplayMode:DEFAULT_MODE").
      // Split at the FIRST colon only — the wire value itself may contain
      // colons (e.g. "Product:urn:product" → name "Product", value
      // "urn:product").
      final separator = subtype.indexOf(':');
      final rawName =
          (separator < 0 ? subtype : subtype.substring(0, separator))
              .trim()
              .replaceAll(RegExp(r'^\$+'), '');
      final wireValue = separator < 0
          ? null
          : subtype.substring(separator + 1).trim();
      final className = _formatClassName(rawName);
      final snakeName = _toSnakeCase(className);
      final fields = subtypeFields[subtype] ?? subtypeFields[rawName] ?? [];

      final subtypeConfig = EntityConfig(
        name: className,
        outputDir: effectiveOutputDir,
        fields: fields,
        generateJson: parentConfig.generateJson,
        generateCopyWithFn: parentConfig.generateCopyWithFn,
        generateCompareTo: parentConfig.generateCompareTo,
        generateFilter: parentConfig.generateFilter,
        dryRun: parentConfig.dryRun,
        subtypeWireValue: wireValue,
      );

      final imports = resolver.resolveSubtypeImports(
        className,
        parentConfig.className,
        fields,
      );

      imports.add(
        "import '../${parentConfig.snakeName}/${parentConfig.snakeName}.dart';",
      );

      final content = EntityTemplateGenerator.generateSubtype(
        parentConfig,
        subtypeConfig,
        parentConfig.className,
        parentConfig.isSealed,
        imports.toList(),
      );

      final entityDir = p.join(effectiveOutputDir, snakeName);
      final filePath = p.join(entityDir, '$snakeName.dart');

      if (!parentConfig.dryRun) {
        await Directory(entityDir).create(recursive: true);
        await File(filePath).writeAsString(content);
      }

      results.add(
        EntityResult(
          className: className,
          filePath: filePath,
          content: content,
          fields: fields,
          created: true,
        ),
      );
    }

    return results;
  }

  Future<void> _updateEnumIndexFile(String enumsDir) async {
    final indexFile = File(p.join(enumsDir, 'index.dart'));
    final allEnums = <String>[];

    await for (final entity in Directory(enumsDir).list()) {
      if (entity is File &&
          entity.path.endsWith('.dart') &&
          !entity.path.contains('index.dart')) {
        final enumName = p.basenameWithoutExtension(entity.path);
        allEnums.add(enumName);
      }
    }

    allEnums.sort();

    final buffer = StringBuffer();
    buffer.writeln('// Auto-generated enum barrel file');
    buffer.writeln('// Exports all enums for easy importing');
    buffer.writeln('// Generated at: ${DateTime.now().toIso8601String()}');
    buffer.writeln();
    buffer.writeln('library enums;');
    buffer.writeln();

    for (final enumName in allEnums) {
      buffer.writeln("export '$enumName.dart';");
    }

    await indexFile.writeAsString(buffer.toString());
  }

  String _insertFields(
    String content,
    String className,
    List<FieldDefinition> fields,
  ) {
    final classPattern = RegExp(r'abstract class \$+' + className + r'\s*\{');
    final classMatch = classPattern.firstMatch(content);

    if (classMatch == null) {
      throw Exception('Could not find class definition');
    }

    final lastFieldPattern = RegExp(r'^\s*\S+\s+get\s+\w+;', multiLine: true);
    final allMatches = lastFieldPattern.allMatches(content).toList();

    int insertPosition;
    if (allMatches.isEmpty) {
      insertPosition = content.indexOf('{', classMatch.end) + 1;
    } else {
      insertPosition = allMatches.last.end;
    }

    final fieldBuffer = StringBuffer();
    for (final field in fields) {
      fieldBuffer.writeln();
      if (field.jsonName != null) {
        fieldBuffer.writeln(
          "  @JsonKey(name: '${EntityTemplateGenerator.escapeDartStringLiteral(field.jsonName!)}')",
        );
      }
      fieldBuffer.writeln('  ${field.fullType} get ${field.name};');
    }

    return content.substring(0, insertPosition) +
        fieldBuffer.toString() +
        content.substring(insertPosition);
  }

  String _formatClassName(String name) {
    var n = name.replaceAll('\$', '');
    final parts = n.split(RegExp(r'[_\s\-]+'));
    return parts
        .map((part) {
          if (part.isEmpty) return '';
          return part[0].toUpperCase() + part.substring(1);
        })
        .join('');
  }

  /// Dart reserved words — a member named after any of these would not compile.
  static const Set<String> _dartKeywords = {
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'base',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'covariant',
    'default',
    'deferred',
    'do',
    'dynamic',
    'else',
    'enum',
    'export',
    'extends',
    'extension',
    'external',
    'factory',
    'false',
    'final',
    'finally',
    'for',
    'function',
    'get',
    'hide',
    'if',
    'implements',
    'import',
    'in',
    'interface',
    'is',
    'late',
    'library',
    'mixin',
    'new',
    'null',
    'of',
    'on',
    'operator',
    'part',
    'required',
    'rethrow',
    'return',
    'sealed',
    'set',
    'show',
    'static',
    'super',
    'switch',
    'sync',
    'this',
    'throw',
    'true',
    'try',
    'typedef',
    'var',
    'void',
    'when',
    'while',
    'with',
    'yield',
  };

  /// True when [name] can be used as a Dart identifier (valid characters and
  /// not a reserved word).
  static bool _isValidDartIdentifier(String name) {
    if (name.isEmpty) return false;
    if (_dartKeywords.contains(name)) return false;
    return RegExp(r'^[a-zA-Z_][a-zA-Z0-9_]*$').hasMatch(name);
  }

  String _toSnakeCase(String text) {
    final camel = _formatClassName(text);
    return camel.replaceAllMapped(RegExp(r'[A-Z]'), (match) {
      final char = match.group(0)!;
      final index = match.start;
      return (index == 0) ? char.toLowerCase() : '_${char.toLowerCase()}';
    });
  }
}
