/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:16:39.573564

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../address/address.dart';

part 'user_with_address.zorphy.dart';
part 'user_with_address.g.dart';

/// UserWithAddress entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $UserWithAddress {

  String get name;
  Address get address;
  String? get phone;
}

