name: zorphy_example
description: Example usage of the zorphy package
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  zorphy_annotation:
    path: ../../zorphy_annotation
  json_annotation: ^4.11.0

dev_dependencies:
  zorphy:
    path: ../
  build_runner: ^2.11.0
  json_serializable:
    git:
      url: https://github.com/arrrrny/json_serializable.dart.git
      ref: analyzer-13
      path: json_serializable

dependency_overrides:
  analyzer: ^13.0.0
