/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-04T13:20:43.301200

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../address/address.dart';

part 'company.g.dart';
part 'company.zorphy.dart';

/// Company entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Company {

  String get name;
  String? get description;
  $Address? get mainAddress;
  List<$Address>? get branches;
}

