/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-04T13:19:32.776696

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../address/address.dart';
import '../user/user.dart';

part 'profile.g.dart';
part 'profile.zorphy.dart';

/// Profile entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Profile {
  $User get user;
  $Address get address;
  List<String> get tags;
}
