/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-04T13:19:14.733118

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

import '../address/address.dart';
part 'user.g.dart';
part 'user.zorphy.dart';

/// User entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $User {

  String get name;
  int get age;
  Status get status;
  String? get phone;

  DateTime get createdAt;
  $Address get address;


}

