import 'dart:io';

import 'package:test/test.dart';

/// Regression test for issue #351: cross-entity concrete reference generates
/// `InvalidType` in the generated `.zorphy.dart` file.
///
/// When a Zorphy entity has a field whose declared type is the CONCRETE form
/// of another Zorphy entity (e.g. `ParentThing? get parent` with no `$`
/// prefix), the analyzer cannot resolve the type during `build_runner`
/// (the concrete class is generated into a `.zorphy.dart` PART file that is
/// not yet in the analysis session). Before the fix, `typeToString` fell
/// back to `InvalidType`, which broke `json_serializable`.
///
/// The fixture lives in `example/lib/various/cross_entity_example.dart` and
/// is regenerated by CI (`dart run build_runner build` in `zorphy/example`)
/// before tests run.
///
/// Secondary finding: a `dynamic` field should NOT become
/// `required dynamic this.x` in the generated constructor — `dynamic` is
/// implicitly nullable, so the `required` must be dropped.
void main() {
  final fixture =
      File('example/lib/various/cross_entity_example.zorphy.dart');

  late String output;

  setUpAll(() {
    if (!fixture.existsSync()) {
      fail(
        'Fixture not generated. Run: cd example && '
        'dart run build_runner build',
      );
    }
    output = fixture.readAsStringSync();
  });

  group('issue #351 — cross-entity concrete reference', () {
    test('field type is the concrete entity name, not InvalidType', () {
      expect(output, contains('final ParentThing? parent;'));
      expect(output, isNot(contains('InvalidType')));
    });

    test('constructor param uses the concrete entity type', () {
      expect(output, contains('ParentThing? this.parent'));
    });

    test('copyWith uses the concrete entity type', () {
      expect(output, contains('ChildThing copyWith({ParentThing? parent,'));
    });

    test('json_serializable succeeded (no InvalidType fallback needed)', () {
      // If json_serializable had failed on InvalidType, build_runner would
      // not have written the .g.dart file and the .zorphy.dart would not
      // reference _$ChildThingFromJson. The fixture's existence + the
      // fromJson factory line together prove the full pipeline succeeded.
      expect(output, contains('factory ChildThing.fromJson'));
    });
  });

  group('issue #351 secondary — dynamic field', () {
    test('constructor param is NOT `required dynamic`', () {
      expect(output, isNot(contains('required dynamic this.data')));
      expect(output, isNot(contains('required dynamic ')));
    });

    test('constructor param is `dynamic this.data`', () {
      expect(output, contains('dynamic this.data'));
    });

    test('field declaration is `final dynamic data;`', () {
      expect(output, contains('final dynamic data;'));
    });
  });
}
