import 'dart:io';

import 'package:test/test.dart';

/// Golden tests for the framework additions behind zuraffa#307:
///
/// - `autoId: true` — the generated concrete constructor takes an optional
///   `String? id` that defaults to `const Uuid().v4()`, so callers never
///   have to supply an identity.
/// - `@ZValueObject` (alias of `@Zorphy(kind: ZorphyKind.valueObject)`) — a
///   value object class with the full entity codegen (equality, copyWith)
///   but no identity requirement.
///
/// The fixtures live in `example/lib/various/` and are regenerated by CI
/// (`dart run build_runner build` in `zorphy/example`) before tests run.
void main() {
  final autoIdFixture = File('example/lib/various/auto_id_example.zorphy.dart');
  final valueObjectFixture = File(
    'example/lib/various/value_object_example.zorphy.dart',
  );

  late String autoIdOutput;
  late String valueObjectOutput;

  setUpAll(() {
    for (final fixture in [autoIdFixture, valueObjectFixture]) {
      if (!fixture.existsSync()) {
        fail(
          'Fixture not generated. Run: cd example && '
          'dart run build_runner build',
        );
      }
    }
    autoIdOutput = autoIdFixture.readAsStringSync();
    valueObjectOutput = valueObjectFixture.readAsStringSync();
  });

  group('autoId', () {
    test('concrete constructor takes optional String? id defaulting to uuid',
        () {
      expect(autoIdOutput, contains('String? id,'));
      expect(
        autoIdOutput,
        contains('this.id = id ?? const Uuid().v4()'),
      );
      // The id must NOT be a required toThis param.
      expect(autoIdOutput, isNot(contains('required String this.id')));
    });

    test('final id field is emitted with the other fields', () {
      expect(autoIdOutput, contains('final String id;'));
    });

    test('copyWith keeps id', () {
      expect(autoIdOutput, contains('id: id ?? this.id,'));
    });
  });

  group('valueObject', () {
    test('generates a plain class with equality and copyWith', () {
      expect(valueObjectOutput, contains('class ParserOptions {'));
      expect(valueObjectOutput, contains('ParserOptions copyWith('));
      expect(valueObjectOutput, contains('bool operator =='));
    });

    test('no identity plumbing is generated', () {
      // No id field, no patch/filter identity surface beyond what the
      // standard preset gives every class.
      expect(valueObjectOutput, isNot(contains('String? id,')));
    });
  });
}
