// Regression tests for issue #117: cross-entity reference resolves
// correctly in the generated `.zorphy.dart` part file.
//
// Issue #117 reported that when a Zorphy entity references another entity
// as a field (cross-entity reference), the generated `<name>.zorphy.dart`
// part file uses the referenced type but never imports it, causing the
// type to resolve to `Object` / `dynamic` and the analyzer to report
// `argument_type_not_assignable`.
//
// Root cause: the `ZorphyGenerator` synthesized the `.zorphy.dart` part
// file without ensuring the parent `<name>.dart` library declares the
// import for the cross-referenced entity type. Part files inherit
// imports from their parent library, so a missing import in the parent
// causes the type to be unresolved in the part file too.
//
// Fix:
// 1. The cast type in `patch_generator.dart` / `json_generator.dart` uses
//    the concrete entity type (via `.replaceAll(r'$', '')`), not the
//    abstract `$Type` form — already on development (commit 1439618).
// 2. The CLI `ImportResolver` emits sibling-entity imports for both
//    `!Type` external and `$Type` non-external fields when the sibling
//    exists on disk — already on development (commit ebef60e).
// 3. The `ZorphyGenerator` now emits a guidance comment in the
//    `.zorphy.dart` part file listing any cross-entity references that
//    are NOT imported in the parent library, so users who hand-author
//    source files can see exactly which imports to add.
//
// The fixture pair lives at:
//   example/lib/various/issue117_ref/issue117_ref.dart
//   example/lib/various/issue117_repro/issue117_repro.dart
//
// The fixture is regenerated by CI (`dart run build_runner build` in
// `zorphy/example`) before tests run.
import 'dart:io';

import 'package:test/test.dart';

void main() {
  final reproFixture =
      File('example/lib/various/issue117_repro/issue117_repro.zorphy.dart');

  late String output;

  setUpAll(() {
    if (!reproFixture.existsSync()) {
      fail(
        'Fixture not generated. Run: cd example && '
        'dart run build_runner build --delete-conflicting-outputs',
      );
    }
    output = reproFixture.readAsStringSync();
  });

  group('issue #117 — cross-entity reference', () {
    test('field declaration uses the concrete entity type', () {
      // The generated concrete class declares `final Issue117Ref ref;`
      // (concrete form), not `final $Issue117Ref ref;` (abstract form).
      // If the import were missing, this would be `InvalidType`.
      expect(output, contains('final Issue117Ref ref;'));
    });

    test('constructor parameter uses the concrete entity type', () {
      expect(output, contains('Issue117Ref this.ref'));
    });

    test('copyWith parameter uses the concrete entity type', () {
      expect(output, contains('Issue117Ref? ref,'));
    });

    test('patchWith cast target is the concrete entity type, not \$Type', () {
      // The cast MUST be `as Issue117Ref` (concrete form) — the previous
      // `as $Issue117Ref` (abstract form) caused argument_type_not_assignable
      // because the abstract supertype cannot be assigned to the concrete
      // constructor parameter type.
      expect(
        RegExp(r'\)\s*as\s+Issue117Ref\b').hasMatch(output),
        isTrue,
        reason: 'patchWith cast must target the concrete Issue117Ref form',
      );
      expect(
        RegExp(r'\)\s*as\s+\$Issue117Ref\b').hasMatch(output),
        isFalse,
        reason: 'patchWith cast must NOT target the abstract \$Issue117Ref '
            'form (issue #117 root cause)',
      );
    });

    test('patchWithIssue117Repro references the patch enum by name', () {
      expect(output, contains('Issue117Repro\$.ref'));
    });

    test('no InvalidType leaks into the generated patch', () {
      expect(output, isNot(contains('InvalidType')));
    });

    test('json_serializable succeeded (no InvalidType fallback needed)', () {
      // If json_serializable had failed on InvalidType, build_runner would
      // not have written the .g.dart file and the .zorphy.dart would not
      // reference _$Issue117ReproFromJson. The fixture's existence + the
      // fromJson factory line together prove the full pipeline succeeded.
      expect(output, contains('factory Issue117Repro.fromJson'));
    });
  });
}
