import 'dart:io';

import 'package:test/test.dart';

/// Regression test for issue #88:
/// "generator: doc-comment '///- ' list-marker lines leak into generated
///  constructor — build fails to parse"
///
/// The Zorphy generator's `recoverTypeFromSource` (in
/// `lib/src/common/helpers.dart`) uses a regex character class
/// `[\w<>,?\s]` to recover the type token for fields whose analyzer
/// type is `InvalidType` (the cross-entity concrete reference case from
/// issue #351). That class excludes `/`, so when a field's preceding
/// doc-comment block uses `///- ` list markers (very common in the
/// zikzak_inappwebview fork's settings docs, e.g.
/// `///- Android native WebView` / `///- iOS`), the regex starts
/// matching AFTER the `///` prefix of each comment line. The remaining
/// text on the comment line (e.g. `macOS`, `iOS`) is then matched as
/// word chars and swept into the captured "type" group, producing a
/// multi-line string like `macOS\n  Bar?`. code_builder emits that
/// string verbatim as the parameter/field type, and dart_style then
/// mis-parses it — the `///` markers vanish as comment delimiters, but
/// the bare token `macOS` survives and leaks into the generated
/// constructor as a stray identifier.
///
/// The fixture lives in `example/lib/various/issue_88_doc_comment_list_marker.dart`
/// and is regenerated by CI (`dart run build_runner build` in
/// `zorphy/example`) before tests run.
void main() {
  final fixture =
      File('example/lib/various/issue_88_doc_comment_list_marker.zorphy.dart');

  late String output;

  setUpAll(() {
    if (!fixture.existsSync()) {
      fail(
        'Fixture not generated. Run: cd example && '
        'dart run build_runner build',
      );
    }
    output = fixture.readAsStringSync();
  });

  group('issue #88 — doc-comment ///- list-marker leak', () {
    test('build succeeded (fixture file was emitted and is parseable)', () {
      // If the build had failed, the .zorphy.dart file would either not
      // exist or would contain broken syntax. The fixture's existence +
      // the test process reaching this point together prove the build
      // succeeded.
      expect(fixture.existsSync(), isTrue);
      expect(output, isNotEmpty);
    });

    test('Foo constructor has clean parameter list (no stray tokens)', () {
      // The bug previously produced:
      //   Foo({bool? this.enabled, macOS
      //     Bar? this.bar, });
      // The `macOS` token (from `///- macOS` in the `bar` field's doc
      // comment) leaked between the two params. After the fix, the
      // constructor must be a single clean line.
      expect(output, contains('Foo({bool? this.enabled, Bar? this.bar})'));
    });

    test('Foo field declarations are clean (no stray tokens)', () {
      // The bug previously produced:
      //   final bool? enabled;
      //
      //   final macOS
      //     Bar? bar;
      // After the fix, both field declarations must be on single lines.
      expect(output, contains('final bool? enabled;'));
      expect(output, contains('final Bar? bar;'));
    });

    test('no `macOS` or `iOS` stray tokens leaked from doc comments', () {
      // Both tokens came from `///- macOS` / `///- iOS` lines in the
      // source doc comments. They must NOT appear as bare identifiers
      // anywhere in the generated source.
      //
      // We use a regex that matches `macOS` / `iOS` as whole-word
      // identifiers (NOT inside a string literal). The generated Foo
      // class has no string literals containing these tokens, so any
      // match is a leak.
      final macosLeak = RegExp(r'\bmacOS\b').hasMatch(output);
      final iosLeak = RegExp(r'\biOS\b').hasMatch(output);
      expect(macosLeak, isFalse,
          reason: 'macOS token leaked from ///- macOS doc-comment line');
      expect(iosLeak, isFalse,
          reason: 'iOS token leaked from ///- iOS doc-comment line');
    });

    test('cross-entity concrete type Bar? was recovered correctly', () {
      // The recovery must still work — `Bar?` (the concrete form of
      // `$Bar`) should appear in the generated source. This proves
      // the fix didn't break the issue #351 cross-entity recovery.
      expect(output, contains('Bar?'));
      expect(output, isNot(contains('InvalidType')));
    });

    test('copyWith constructor is clean too', () {
      // The copyWith constructor also has the field type, so it would
      // have leaked the same way. Verify it's clean.
      expect(output, contains('Foo copyWith({bool? enabled, Bar? bar})'));
    });
  });
}
