import 'dart:io';

import 'package:test/test.dart';

/// Regression tests for issue #304.
///
/// `zfa entity create -n Sub --extends Base` used to emit
///   `abstract class $Sub implements Base { ... }`
/// (bare name, no `$` prefix) in the source abstract class. The analyzer
/// cannot resolve `Base` at source-analysis time because `Base` is the
/// GENERATED CONCRETE class name (emitted by zorphy into the .zorphy.dart
/// file later). The implements clause was silently dropped, and the
/// generated concrete class lost the relationship to `Base` — breaking
/// `isA<Base>()` checks and union-type dispatch.
///
/// The fix has two parts:
///
///   1. **zfa CLI** (`entity_template_generator.dart`): the `--extends`
///      flag now emits `implements $Base` (with `$` prefix) instead of
///      `implements Base` (bare name). The analyzer resolves `$Base`
///      (the source abstract class) directly.
///
///   2. **zorphy codegen** (`interface_collector.dart`): a recovery
///      path parses the source text of the class declaration, finds
///      unresolved `implements` clauses, resolves each name against
///      `allAnnotatedClasses` (trying `$Name` and `$$Name` variants),
///      and adds the recovered interface to `metadata.interfaces` with
///      the source class name (including the `$` prefix). This handles
///      EXISTING source files generated by the old zfa CLI.
///
/// Both paths produce the same generated output:
///   `class Sub extends Base { ... }`
/// making `isA<Base>()` hold at runtime via inheritance (not implements,
/// which would require re-implementing all of Base's generated methods:
/// copyWithBase, patchWithBase, ==, hashCode, toString, ...).
void main() {
  final fixture = File('example/lib/various/issue_304_extends.zorphy.dart');
  late String output;

  setUpAll(() {
    if (!fixture.existsSync()) {
      fail(
        'Fixture not generated. Run: cd example && '
        'dart run build_runner build --delete-conflicting-outputs',
      );
    }
    output = fixture.readAsStringSync();
  });

  group('#304 — zfa entity create --extends propagates interface', () {
    test(
      'scenario 1: \$-prefixed source (NEW zfa CLI) → concrete extends base',
      () {
        // The generated concrete class should `extends BaseDollarPrefixed`
        // (NOT `implements BaseDollarPrefixed` — implements would fail to
        // compile because BaseDollarPrefixed has many generated methods
        // that the subclass would need to re-implement).
        expect(
          output,
          contains('class SubDollarPrefixed extends BaseDollarPrefixed'),
          reason:
              'The generated concrete class must extend the base concrete '
              'class so isA<BaseDollarPrefixed>() holds at runtime. '
              'Using implements would fail to compile (non_abstract_class_'
              'inherits_abstract_member) because BaseDollarPrefixed has '
              'copyWithBaseDollarPrefixed, patchWithBaseDollarPrefixed, '
              'etc. that the subclass would need to re-implement.',
        );

        // The generated concrete class must NOT use `implements` for the
        // base class (it should use `extends`).
        expect(
          output,
          isNot(contains('class SubDollarPrefixed implements')),
          reason:
              'implements would require re-implementing all of '
              'BaseDollarPrefixed\'s generated methods. extends is the '
              'correct relationship for concrete-to-concrete subtyping.',
        );
      },
    );

    test('scenario 2: bare-name source (OLD zfa CLI) → recovery logic '
        'produces the same extends relationship', () {
      // The recovery logic in InterfaceCollector should resolve
      // `BareBase` (bare name) to `$BareBase` (source class) and
      // produce `class SubBareName extends BareBase`.
      expect(
        output,
        contains('class SubBareName extends BareBase'),
        reason:
            'The recovery logic should resolve the bare name `BareBase` '
            'against allAnnotatedClasses (trying `\$BareBase`), add it '
            'to metadata.interfaces with the source class name '
            '(`\$BareBase`), and produce `extends BareBase` on the '
            'generated concrete class. This handles existing source '
            'files generated by the old zfa CLI (which emitted bare '
            'names).',
      );

      expect(
        output,
        isNot(contains('class SubBareName implements')),
        reason:
            'Same as scenario 1: implements would fail to compile. '
            'The recovery logic must route to extends, not implements.',
      );
    });

    test('generated concrete classes compile (no abstract member errors)', () {
      // The generated file should not contain the markers of a broken
      // implements relationship. If the codegen had used `implements`
      // instead of `extends`, the generated class would be missing
      // copyWithBase*/patchWithBase* methods (which exist on the base
      // concrete class but not on the subclass), causing
      // non_abstract_class_inherits_abstract_member errors.
      //
      // We assert the extends relationship is present (which inherits
      // all methods, avoiding the error).
      expect(
        output,
        contains('class SubDollarPrefixed extends BaseDollarPrefixed'),
      );
      expect(output, contains('class SubBareName extends BareBase'));
    });

    test('base classes are still generated as standalone concrete classes', () {
      // The base classes should be generated as regular concrete classes
      // (no extends/implements on them).
      expect(
        output,
        contains('class BaseDollarPrefixed {'),
        reason:
            'BaseDollarPrefixed has no --extends, so it should be a '
            'standalone concrete class.',
      );
      expect(
        output,
        contains('class BareBase {'),
        reason:
            'BareBase has no --extends, so it should be a standalone '
            'concrete class.',
      );
    });
  });
}
