import 'dart:io';

import 'package:test/test.dart';

/// Golden tests for ZorphyPreset gating, asserted against the generated
/// example fixture `example/lib/various/preset_example.zorphy.dart`.
///
/// The fixture is regenerated by CI (`dart run build_runner build` in
/// `zorphy/example`) before tests run; if the file is missing these tests
/// fail with instructions.
void main() {
  final fixture = File('example/lib/various/preset_example.zorphy.dart');
  late String output;

  setUpAll(() {
    if (!fixture.existsSync()) {
      fail(
        'Fixture not generated. Run: cd example && '
        'dart run build_runner build --delete-conflicting-outputs',
      );
    }
    output = fixture.readAsStringSync();
  });

  group('lean preset', () {
    test('emits the core class with copyWith and equality', () {
      expect(output, contains('class LeanUser'));
      expect(output, contains('LeanUser copyWith('));
      expect(output, contains('bool operator =='));
    });

    test('emits NO patch/filter/fields/compareTo/property-helper symbols '
        'for the lean class', () {
      expect(output, isNot(contains('LeanUserPatch')));
      expect(output, isNot(contains('LeanUserFields')));
      expect(output, isNot(contains('LeanUserField')));
      expect(output, isNot(contains('compareToLeanUser')));
      expect(output, isNot(contains('patchWithLeanUser')));
      // No property-helper extension members for LeanUser
      expect(output, isNot(contains('LeanUserPropertyHelpers')));
    });
  });

  group('lean preset + generatePatch override', () {
    test('emits the patch API for the overridden class', () {
      expect(output, contains('class LeanPatchedTodoPatch'));
      expect(output, contains('patchWithLeanPatchedTodo'));
    });

    test('still omits the other gated features', () {
      expect(output, isNot(contains('LeanPatchedTodoFields')));
      expect(output, isNot(contains('compareToLeanPatchedTodo')));
    });
  });

  group('full preset', () {
    test('emits standard features plus copyWithFn', () {
      expect(output, contains('class FullConfig'));
      expect(output, contains('FullConfig copyWithFn('));
      expect(output, contains('FullConfigPatch'));
      expect(output, contains('FullConfigFields'));
      expect(output, contains('compareToFullConfig'));
    });
  });
}
