/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:58:38.399544

import 'package:zorphy_annotation/zorphy_annotation.dart';
part 'shape.zorphy.dart';
part 'shape.g.dart';

/// Shape entity
@Zorphy(
  generateJson: true,
  generateCompareTo: true,
  explicitSubTypes: [$Circle, $Rectangle],
)
abstract class $$Shape {
  String get color;
}

@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Circle implements $$Shape {}

@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Rectangle implements $$Shape {}
