/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:16:38.868599

import 'package:zorphy_annotation/zorphy_annotation.dart';
part 'address.zorphy.dart';
part 'address.g.dart';

/// Address entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Address {

  String get street;
  String get city;
  String get postalCode;
}

