/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-04T13:24:22.932885

import 'package:zorphy_annotation/zorphy_annotation.dart';
part 'test_order.zorphy.dart';
part 'test_order.g.dart';

/// TestOrder entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $TestOrder {
  String get name;
}
