/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:58:38.399544

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../circle/circle.dart';
import '../rectangle/rectangle.dart';

part 'shape.zorphy.dart';

/// Shape entity
@Zorphy(
  generateJson: true,
  generateCompareTo: true,
  explicitSubTypes: [$Circle, $Rectangle],
  nonSealed: true,
)
abstract class $$Shape {
  String get color;
}
