/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:16:40.382117

import 'package:zorphy_annotation/zorphy_annotation.dart';
part 'payment_method.zorphy.dart';
part 'payment_method.g.dart';

/// PaymentMethod entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $$PaymentMethod {

  String get displayName;
}

