import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../models/entity_config.dart';

/// Generates entity template code
class EntityTemplateGenerator {
  const EntityTemplateGenerator._();

  /// Escapes a string value for safe interpolation into a Dart string
  /// literal. Handles apostrophes, backslashes, quotes, dollar signs, and
  /// line breaks. Mirrors `_escapeDartStringLiteral` in json_generator.dart.
  static String _escapeDartStringLiteral(String value) {
    return value
        .replaceAll('\\', '\\\\') // backslash must be first
        .replaceAll("'", "\\'") // single quote
        .replaceAll('"', '\\"') // double quote
        .replaceAll('\$', '\\\$') // dollar sign
        .replaceAll('\n', '\\n') // newline
        .replaceAll('\r', '\\r') // carriage return
        .replaceAll('\t', '\\t'); // tab
  }

  /// Normalizes a subtype name the same way [EntityCreator._formatClassName]
  /// does, so annotation references match the generated subtype classes
  /// (e.g. `default_display_mode:DEFAULT_MODE` → `DefaultDisplayMode`).
  static String _formatSubtypeClassName(String subtype) {
    final name = subtype
        .split(':')
        .first
        .replaceAll(r'$', '')
        .trim();
    final parts = name.split(RegExp(r'[_\s\-]+'));
    return parts
        .map((part) {
          if (part.isEmpty) return '';
          return part[0].toUpperCase() + part.substring(1);
        })
        .join('');
  }

  /// Generate entity file content
  static String generate(EntityConfig config, List<String> imports) {
    final buffer = StringBuffer();

    _writeHeader(buffer);
    _writeImports(
      buffer,
      imports,
      includeUuidImport: config.autoId,
    );
    _writePartDirectives(buffer, config);
    _writeClassDefinition(buffer, config);

    return buffer.toString();
  }

  /// Generate subtype entity file content
  static String generateSubtype(
    EntityConfig parentConfig,
    EntityConfig subtypeConfig,
    String parentClassName,
    bool isSealed,
    List<String> imports,
  ) {
    final buffer = StringBuffer();

    _writeHeader(buffer);
    _writeImports(buffer, imports);
    _writeSubtypePartDirectives(buffer, subtypeConfig);
    _writeSubtypeClassDefinition(
      buffer,
      subtypeConfig,
      parentClassName,
      isSealed,
    );

    return buffer.toString();
  }

  static void _writeHeader(StringBuffer buffer) {
    buffer.writeln('// Auto-generated by Zorphy');
    buffer.writeln('// Generated at: ${DateTime.now().toIso8601String()}');
    buffer.writeln();
  }

  static void _writeImports(
    StringBuffer buffer,
    List<String> imports, {
    bool includeUuidImport = false,
  }) {
    buffer.writeln(
      "import 'package:zorphy_annotation/zorphy_annotation.dart';",
    );

    if (includeUuidImport) {
      buffer.writeln("import 'package:uuid/uuid.dart';");
    }

    if (imports.isNotEmpty) {
      final sorted = imports.toList()..sort();
      for (final import in sorted) {
        buffer.writeln(import);
      }
    }
    buffer.writeln();
  }

  static void _writePartDirectives(StringBuffer buffer, EntityConfig config) {
    buffer.writeln("part '${config.snakeName}.zorphy.dart';");

    if (config.generateJson && !config.isSealed && !config.isNonSealed) {
      buffer.writeln("part '${config.snakeName}.g.dart';");
    }
    buffer.writeln();
  }

  static void _writeSubtypePartDirectives(
    StringBuffer buffer,
    EntityConfig config,
  ) {
    buffer.writeln("part '${config.snakeName}.zorphy.dart';");
    if (config.generateJson) {
      buffer.writeln("part '${config.snakeName}.g.dart';");
    }
    buffer.writeln();
  }

  static void _writeClassDefinition(StringBuffer buffer, EntityConfig config) {
    final annotationOptions = _buildAnnotationOptions(config);

    buffer.writeln('/// ${config.className} entity');
    buffer.writeln('@Zorphy(${annotationOptions.join(', ')})');

    final abstractClassName = config.isSealed || config.isNonSealed
        ? '\$\$${config.className}'
        : '\$${config.className}';

    if (config.extendsInterface != null) {
      // Issue #304 fix: normalize the extends interface to use the
      // `$`-prefixed source abstract class name. The user passes the
      // public concrete class name (e.g., `AuthenticationResult`), but
      // the source abstract class that the analyzer can resolve is
      // `$AuthenticationResult`. Without the `$` prefix, the analyzer
      // silently drops the implements clause (the concrete class doesn't
      // exist at source-analysis time), and the generated concrete class
      // loses the implements clause — breaking `isA<Base>()` checks.
      //
      // If the user already passed a `$`-prefixed name (e.g., `$$Shape`
      // for a sealed class), use it as-is.
      final extendsInterface = _normalizeExtendsInterface(
        config.extendsInterface!,
      );
      buffer.writeln(
        'abstract class $abstractClassName implements $extendsInterface {',
      );
    } else {
      buffer.writeln('abstract class $abstractClassName {');
    }
    buffer.writeln();

    _writeFields(
      buffer,
      config.fields,
      prependAutoId: config.autoId,
    );

    buffer.writeln('}');
    buffer.writeln();
  }

  static void _writeSubtypeClassDefinition(
    StringBuffer buffer,
    EntityConfig config,
    String parentClassName,
    bool parentIsSealed,
  ) {
    final annotationOptions = <String>[];
    if (config.generateJson) annotationOptions.add('generateJson: true');
    if (config.generateCopyWithFn)
      annotationOptions.add('generateCopyWithFn: true');
    if (config.generateCompareTo)
      annotationOptions.add('generateCompareTo: true');
    if (config.generateFilter) annotationOptions.add('generateFilter: true');
    if (config.subtypeWireValue != null) {
      annotationOptions.add(
        "subtypeWireValue: '${_escapeDartStringLiteral(config.subtypeWireValue!)}'",
      );
    }

    buffer.writeln(
      '/// ${config.className} entity (subtype of $parentClassName)',
    );
    buffer.writeln('@Zorphy(${annotationOptions.join(', ')})');

    final parentRef = parentIsSealed || config.isNonSealed
        ? '\$\$$parentClassName'
        : '\$$parentClassName';
    buffer.writeln(
      'abstract class \$${config.className} implements $parentRef {',
    );

    if (config.fields.isNotEmpty) {
      buffer.writeln();
      _writeFields(buffer, config.fields);
    }

    buffer.writeln('}');
    buffer.writeln();
  }

  /// Normalize the extends interface name to use the `$`-prefixed source
  /// abstract class name.
  ///
  /// - `AuthenticationResult` → `\$AuthenticationResult`
  /// - `\$AuthenticationResult` → `\$AuthenticationResult` (no change)
  /// - `\$\$Shape` → `\$\$Shape` (no change, sealed class)
  ///
  /// This ensures the analyzer can resolve the implements target at
  /// source-analysis time (the source abstract class exists; the generated
  /// concrete class does not).
  static String _normalizeExtendsInterface(String name) {
    if (name.startsWith(r'$')) return name;
    return '\$$name';
  }

  static List<String> _buildAnnotationOptions(EntityConfig config) {
    final options = <String>[];
    if (config.kind != ZorphyKind.entity) {
      options.add('kind: ZorphyKind.${config.kind.name}');
    }
    if (config.autoId) options.add('autoId: true');
    if (config.generateJson) options.add('generateJson: true');
    if (config.generateCopyWithFn) options.add('generateCopyWithFn: true');
    if (config.generateCompareTo) options.add('generateCompareTo: true');
    if (config.isNonSealed) options.add('nonSealed: true');
    if (config.generateFilter) options.add('generateFilter: true');
    if (config.typeKey != null) {
      options.add("typeKey: '${_escapeDartStringLiteral(config.typeKey!)}'");
    }
    if (config.subtypeWireValue != null) {
      options.add(
        "subtypeWireValue: '${_escapeDartStringLiteral(config.subtypeWireValue!)}'",
      );
    }

    if (config.explicitSubtypes.isNotEmpty) {
      // Strip optional :wireValue suffix from subtype names and normalize
      // them with the same class-name rules EntityCreator uses, so the
      // annotation references match the generated subtype classes.
      final subtypes = config.explicitSubtypes
          .map((s) => '\$${_formatSubtypeClassName(s)}')
          .join(', ');
      options.add("explicitSubTypes: [$subtypes]");
    }

    return options;
  }

  /// Generate inline subtype (for sealed classes)
  static String generateInlineSubtype(
    String subtypeName,
    String parentClassName,
    bool parentIsSealed,
    List<FieldDefinition> fields,
    EntityConfig parentConfig,
  ) {
    final buffer = StringBuffer();

    final annotationOptions = <String>[];
    if (parentConfig.generateJson) annotationOptions.add('generateJson: true');
    if (parentConfig.generateCopyWithFn)
      annotationOptions.add('generateCopyWithFn: true');
    if (parentConfig.generateCompareTo)
      annotationOptions.add('generateCompareTo: true');
    if (parentConfig.generateFilter)
      annotationOptions.add('generateFilter: true');

    buffer.writeln('/// $subtypeName entity (subtype of $parentClassName)');
    buffer.writeln('@Zorphy(${annotationOptions.join(', ')})');

    final parentRef = parentIsSealed || parentConfig.isNonSealed
        ? '\$\$$parentClassName'
        : '\$$parentClassName';
    buffer.writeln('abstract class \$$subtypeName implements $parentRef {');

    if (fields.isNotEmpty) {
      buffer.writeln();
      _writeFields(buffer, fields);
    }

    buffer.writeln('}');
    buffer.writeln();

    return buffer.toString();
  }

  /// Writes the getter declarations for [fields], emitting an
  /// `@JsonKey(name: ...)` annotation above a getter when the field's
  /// [FieldDefinition.jsonName] differs from its Dart [FieldDefinition.name].
  ///
  /// When [prependAutoId] is true (and no field is already named `id`), a
  /// `String get id;` declaration is written first — the `autoId: true`
  /// annotation makes the concrete constructor default it to `Uuid().v4()`.
  static void _writeFields(
    StringBuffer buffer,
    List<FieldDefinition> fields, {
    bool prependAutoId = false,
  }) {
    final hasIdField = fields.any((f) => f.name == 'id');
    if (prependAutoId && !hasIdField) {
      buffer.writeln('  String get id;');
    }
    for (final field in fields) {
      if (field.jsonName != null) {
        buffer.writeln("  @JsonKey(name: '${field.jsonName}')");
      }
      buffer.writeln('  ${field.fullType} get ${field.name};');
    }
  }
}
