analyzer:
  exclude:
    - bin/**
    - lib/*.g.dart
    - example/test/_unsupported/**
    - example/build_output/**
    - .dart_tool/**
    - example/lib/_unsupported/**
    - test/**
    - test_builder.dart
