/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-04T17:07:47.215229

import 'package:zorphy_annotation/zorphy_annotation.dart';
part 'simple_person.zorphy.dart';
part 'simple_person.g.dart';

/// SimplePerson entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $SimplePerson {
  String get name;
  int get age;
}
