/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:16:41.828140

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../payment_method/payment_method.dart';

part 'pay_pal.zorphy.dart';
part 'pay_pal.g.dart';

/// PayPal entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PayPal implements PaymentMethod {

  String get email;
}

