/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06T20:16:38.165707

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'account.zorphy.dart';
part 'account.g.dart';

/// Account entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Account {

  String get username;
  UserStatus get status;
  DateTime get createdAt;
}

