/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-06 20:58:38.414917

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../shape/shape.dart';

part 'circle.zorphy.dart';
part 'circle.g.dart';

/// Circle entity (subtype of Shape)
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Circle implements $$Shape {}
