/// Auto-generated by Zorphy CLI
/// Generated at: 2026-02-04T13:23:11.540558

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'user_account.g.dart';
part 'user_account.zorphy.dart';

/// UserAccount entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $UserAccount {
  String get username;
  String get email;
  AccountStatus get status;
  UserRole get role;
}
